/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;
import BlockChain.NodeData;

/**
 *
 * @author Jimmy
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    byte contador;
    
    public frmInicio() {
        initComponents();        
        
        this.contador = 0;
        
        this.txtNombreServidor.setText("SV");
        this.txtDireccionIPServidor.setText("127.0.0.1");
        this.txtNumeroSocketServidor.setText("7000");
        
        this.txtNombreServidor.setEditable(false);
        this.txtDireccionIPServidor.setEditable(false);
        this.txtNumeroSocketServidor.setEditable(false);
        this.txtNombreCliente.setEditable(false);
        this.txtDireccionIPCliente.setEditable(false);
        this.txtNumeroSocketCliente.setEditable(false);
        this.btnCrearRecepcionista.setEnabled(false);
        this.btnCrearDoctor.setEnabled(false);
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDireccionIPServidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreServidor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroSocketServidor = new javax.swing.JTextField();
        btnCrearServidor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDireccionIPCliente = new javax.swing.JTextField();
        btnCrearDoctor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroSocketCliente = new javax.swing.JTextField();
        btnCrearRecepcionista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Crear Servidor");

        jLabel2.setText("Nombre del servidor:");

        jLabel3.setText("Direccion IP:");

        jLabel4.setText("Número de puerto/socket:");

        btnCrearServidor.setText("Crear Servidor");
        btnCrearServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearServidorActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre del trabajador:");

        jLabel6.setText("Direccion IP:");

        btnCrearDoctor.setText("Crear Doctor");
        btnCrearDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDoctorActionPerformed(evt);
            }
        });

        jLabel7.setText("Número de puerto/socket:");

        btnCrearRecepcionista.setText("Crear Recepcionista");
        btnCrearRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRecepcionistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDireccionIPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroSocketServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrearRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrearDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccionIPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroSocketCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccionIPServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNumeroSocketServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCrearServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionIPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumeroSocketCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrearRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRecepcionistaActionPerformed
        // TODO add your handling code here:
        NodeData nodeData = new NodeData(
                txtNombreCliente.getText(),
                txtDireccionIPCliente.getText(),
                Integer.parseInt(txtNumeroSocketCliente.getText())
        );
        
        this.txtNombreCliente.setText("DR. Retana");
        this.txtDireccionIPCliente.setText("127.0.0.1");
        this.txtNumeroSocketCliente.setText("8001");
        
        this.btnCrearRecepcionista.setEnabled(false);
        this.btnCrearDoctor.setEnabled(true);

        frmRecepcionista recepcionista = new frmRecepcionista();
        recepcionista.configurar(nodeData);
        recepcionista.setVisible(true);
    }//GEN-LAST:event_btnCrearRecepcionistaActionPerformed

    private void btnCrearDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDoctorActionPerformed
        // TODO add your handling code here:
        NodeData nodeData = new NodeData(
                txtNombreCliente.getText(),
                txtDireccionIPCliente.getText(),
                Integer.parseInt(txtNumeroSocketCliente.getText())
        );
        
        this.txtNombreCliente.setText("DR. Ramos");
        this.txtDireccionIPCliente.setText("127.0.0.1");
        this.txtNumeroSocketCliente.setText("8002");

        frmDoctor doctor = new frmDoctor();
        doctor.configurar(nodeData);
        doctor.setVisible(true);
        
        this.contador++;
        
        if(contador == 2){
            this.txtNombreCliente.setText("");
            this.txtDireccionIPCliente.setText("");
            this.txtNumeroSocketCliente.setText("");
            
            this.btnCrearDoctor.setEnabled(false);
        }
    }//GEN-LAST:event_btnCrearDoctorActionPerformed

    private void btnCrearServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearServidorActionPerformed
        // TODO add your handling code here:
        NodeData nodoServidor = new NodeData(
                this.txtNombreServidor.getText(),
                this.txtDireccionIPServidor.getText(),
                Integer.parseInt(this.txtNumeroSocketServidor.getText())
        );
        
        this.txtNombreServidor.setText("");
        this.txtDireccionIPServidor.setText("");
        this.txtNumeroSocketServidor.setText("");
                
        this.txtNombreCliente.setText("MILO J");
        this.txtDireccionIPCliente.setText("127.0.0.1");
        this.txtNumeroSocketCliente.setText("8000");
        
        this.btnCrearServidor.setEnabled(false);
        this.btnCrearRecepcionista.setEnabled(true);
        
        frmServidor servidor = new frmServidor(nodoServidor);
        servidor.setVisible(true);        
    }//GEN-LAST:event_btnCrearServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearDoctor;
    private javax.swing.JButton btnCrearRecepcionista;
    private javax.swing.JButton btnCrearServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtDireccionIPCliente;
    private javax.swing.JTextField txtDireccionIPServidor;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreServidor;
    private javax.swing.JTextField txtNumeroSocketCliente;
    private javax.swing.JTextField txtNumeroSocketServidor;
    // End of variables declaration//GEN-END:variables
}
